import {ADD_ANSWER} from '../actions/index';

const defaultAnswers = {
    android: false,
    ios: false,
    blackBerry: false,
    windowsPhone: false,
    linux: false,
    macOs: false,
    windows: false,
    web: false,
    iOSnonMac: false,
    winNonWin: false,
    size: 1,
    price: 500,
    nativeLook: false,
    singleUi: true,
    multithreading: false,
    camera: false,
    microphone: false,
    video: false,
    audio: false,
    gps: false,
    accelerometer: false,
    gyro: false,
    deviceState: false,
    background: false,
    push: false,
    invokeNative: false,
    crash: false,
    complex: -1,
    popularity: 0,
    designer: false,
    tablet: false,
    osOverrides: false,
    files: false,
    appProperties: false,
    couchbase: false,
    realm: false,
    sqlite: false,
    otherDb: false,
    bluetooth: false,
    nfc: false,
    fingerprint: false,
    barcode: false,
    alexa: false,
    cortana: false,
    now: false,
    siri: false,
    debug: false,
    unit: false,
    uiTesting: false,
    profiling: false,
    angular: false,
    basic: false,
    cpp: false,
    csharp: false,
    delphi: false,
    js: false,
    java: false,
    lua: false,
    python: false,
    react: false,
    ruby: false,
    codefree: false,
    mbaas: false,
    browser: false,
    call: false,
    multitest: false,
    ci: false,
    closedGroups: false,
    openGl: false,
    games: false,
    avr: false
};

export default function (state = defaultAnswers, action) {
    switch (action.type) {
        case ADD_ANSWER:
            return Object.assign({}, action.payload.oldAnswers, action.payload.newSubset)
    }

    return state;
}